### ISSUE TITLE
Small Dutch translation bugs

### ISSUE THREAD

**Issue by SoongNoonien** [SoongNoonien/plattenalbum#101]
@rien333 Sorry, I didn't notice these yesterday.

In the new updated Dutch translations there are a view issues with mnemonics. "Album aan wachtrij toevoegen" misses a mnemonic:
 
![Bildschirmfoto vom 2024-03-10 09-38-31](https://github.com/SoongNoonien/plattenalbum/assets/49582808/99d68e8e-a9ac-4665-a86e-f14a324a5565)

And here "S" is used twice:

![Bildschirmfoto vom 2024-03-10 09-39-00](https://github.com/SoongNoonien/plattenalbum/assets/49582808/1988231d-284b-447a-94ec-f8e5c376e891)

Here "T" is used twice. Another small thing, should "toevoegen" be capitalized here?

![Bildschirmfoto vom 2024-03-10 09-39-27](https://github.com/SoongNoonien/plattenalbum/assets/49582808/9f93d8ca-5b0a-4fe4-b7df-577281dcfe42)

And in the settings there are two toggles using "M".

**Comment by rien333** [comment]
My bad! Will fix asap.

**Comment by rien333** [comment]
> > Not sure why, but Gnome doesn't display mnemonics for me, so must have missed these.
> 
> They are a bit tricky to show, I'm also a bit confused why. If the menu is open you have to press first the `alt` key and then some arrow key. I'm sure if this is intended.

idk, maybe a thing that is on its way out? I kind of like them, now that I know how to use and see them. 

Other adwaita apps seem to behave similarly, btw (with the expection of the window/<kbd>alt+space</kbd> menu), whereas gtk3 apps only require an <kbd>Alt</kbd> press.
