### ISSUE TITLE
ALL item

### ISSUE THREAD

**Issue by Louson** [SoongNoonien/plattenalbum#103]
Hello, may we add a extra item 'All' to see all albums from all artists.

Details: The first view shows artists. Clicking on an artist shows album from that artist.

Clicking instead on 'All' would show all albums. Then if there is also a 'All' item in albums, we could have all songs.

**Comment by rien333** [comment]
> Hello, may we add a extra item 'All' to see all albums from all artists.

What value does this add? I don't see how scrolling through a list of 1000+ albums would be particularity useful, compared to the navigational mechanisms that have been implemented already 

Moreover, I'm guessing it would be slow as heck, especially if you part of your music library comes from NFS shares.

**Comment by Louson** [comment]
Let's say you don't know what to listen. Looking at all albums is a nice way to pick some Music.

I understand it may be slow through distant NFS, but probably not on the host or through local network. Perhaps as an opt-in option ?

That's more a suggestion than a request. No problem if you don't want to make it (or if that's too hard)

**Comment by SoongNoonien** [comment]
> What value does this add? I don't see how scrolling through a list of 1000+ albums would be particularity useful,...

Yes, I'd say so too.

> Moreover, I'm guessing it would be slow as heck, especially if you part of your music library comes from NFS shares. (at any rate, loading album covers from an NFS share can already be slow when previewing only ~6 albums)

It's true, this is too slow without a cover cache which I won't implement.

**Comment by Louson** [comment]
> > Moreover, I'm guessing it would be slow as heck, especially if you part of your music library comes from NFS shares. (at any rate, loading album covers from an NFS share can already be slow when previewing only ~6 albums)
> 
> It's true, this is too slow without a cover cache which I won't implement.

Ok, I can understand that. Sorry for bothering
