### ISSUE TITLE
Multiple selection

### ISSUE THREAD

**Issue by Louson** [SoongNoonien/plattenalbum#104]
Hello,

It would be nice to be able to select several items and have matching albums. Ctrl+A might select all items.

**Comment by rien333** [comment]
> It would be nice to be able to select several items

I'm not sure if I follow a 100% — what items? Please be more explicit about what you want next time —  say, by including detailed examples, or annotated screenshots.

However, I think being able to "select more than one item" might have some use cases in some parts of the application. For instance, currently, you will have to remove songs from the queue either one-by-one, or all at the same time. It might be nice to be able to shift-click on songs, and select ranges of songs that way. 

> select several items and _have matching albums_

This I also don't follow.

**Comment by SoongNoonien** [comment]
I think "items" mean artists here, don't they?

**Comment by Louson** [comment]
yes, it does. I see my issue wasn't very clear.

The goal was same as #103, but an other way. However, the issue remains the cover cache. No big deal, thanks for the app anyway
