### ISSUE TITLE
MPRIS duplication

### ISSUE THREAD

**Issue by rien333** [SoongNoonien/plattenalbum#105]
This might be better as a discussion question, but oh well. 

I've noticted that the option to enable/disable plattenalbum's own MPRIS support was recently removed. Instead, plattenalbum's own MPRIS interface is now always enabled.

In my case, this lead to duplicate entries in my already full notification area: 
![image](https://github.com/SoongNoonien/plattenalbum/assets/10417027/c882528f-b11f-4ea6-9a38-bee5b1f6b55d)

The cause behind this duplication is that I approach plattenalbum as an mpd client, and hence, run my own mpd MPRIS server ([arch wiki entry](https://wiki.archlinux.org/title/Music_Player_Daemon/Tips_and_tricks#MPRIS_support)). This gives me control over my mpd session and the rest of my audio apps (even by way of my phone), without ever opening plattenalbum. 

Also note that  programs (such as the popular [rescrobbled](https://github.com/InputUsername/rescrobbled)) might inspect MPRIS for e.g. last.fm scrobbling. Having an always-on MPRIS implementation at the mpd-level works better for  use cases such as continuous MPRIS-based scrobbling. 

----

Would you be willing to reconsider this change? I think outsourcing MPRIS to the mpd music server, instead of reinventing the wheel client-side, is actually more in line with the mpd philosophy, and also with the fact that plattenalbum desires to be small, simple, and easily maintainable.  Indeed, glancing at the mpd clients on the [arch wiki](https://wiki.archlinux.org/title/Music_Player_Daemon#Clients) reveals that most — if not all?  —  lack their own MPRIS implementation. 

A major downside of removing this feature, of course, is that offering build-in MPRIS support is far more friendly to newcomers. However, mpd is not the for the faint of hearth anyway, so maybe that problem can be mitigated by linking users to mpd MPRIS implementations in the README file. I'm sure they will able to manage. 

An alternative, but potentially hacky solution is to check if mpd is already subscribed to the MPRIS interface, and enabling plattenalbum's own MPRIS implementation based on that. For instance, running `playerctl -l` gives me:

```
de.wagnermartin.Plattenalbum
firefox.instance_1_86
mpd
spotify
```

**Comment by SoongNoonien** [comment]
> Would you be willing to reconsider this change?

I've made MPRIS optional again. I removed this option while reworking the settings because it was the only setting remaining which requires a restart of the program and I thought that it is not so important. Maybe I'll remove the need for restarting when I get to it. This should be relatively easy.

> Also note that programs (such as the popular [rescrobbled](https://github.com/InputUsername/rescrobbled)) might inspect MPRIS for e.g. last.fm scrobbling. Having an always-on MPRIS implementation at the mpd-level works better for use cases such as continuous MPRIS-based scrobbling.

Didn't know this existed. I only knew [mpdscribble](https://www.musicpd.org/clients/mpdscribble/), but this is not very useful if multiple audio players are used.

> I think outsourcing MPRIS to the mpd music server, instead of reinventing the wheel client-side, is actually more in line with the mpd philosophy, and also with the fact that plattenalbum desires to be small, simple, and easily maintainable.

But I don't like to install another client just for the MPRIS interface. I may be a fairly untypical MPD user but I only have one client in use. Another advantage of the integration of MPRIS inside Plattenalbum is that there is an actual association between the window of the client an the representation of the MPRIS controls in the desktop. In GNOME for example this has the effect that clicking on the MPRIS controls in the  notification area brings the client to focus, which I use from time to time.

> Indeed, glancing at the mpd clients on the [arch wiki](https://wiki.archlinux.org/title/Music_Player_Daemon#Clients) reveals that most — if not all? — lack their own MPRIS implementation.

Cantata has one. But it has some bugs which won't be fixed as it is unmaintained.

**Comment by rien333** [comment]
> In GNOME for example this has the effect that clicking on the MPRIS controls in the notification area brings the client to focus, which I use from time to time.

Yeah, this is something I miss with [mpd-mpris](https://github.com/natsukagami/mpd-mpris)! 

Thanks for looking into this.

**Comment by rien333** [comment]
> In GNOME for example this has the effect that clicking on the MPRIS controls in the notification area brings the client to focus, which I use from time to time.

I made a silly patch that hacks this into `[mpd-mpris](https://github.com/natsukagami/mpd-mpris)`, since I do indeed like this functionality: 

``` diff
diff --git a/introspect.go b/introspect.go
index 63c688c..913f853 100644
--- a/introspect.go
+++ b/introspect.go
@@ -43,6 +43,11 @@ func (i *Instance) IntrospectNode() *introspect.Node {
 						Type:   "as",
 						Access: "read",
 					},
+					introspect.Property{
+						Name:   "DesktopEntry",
+						Type:   "as",
+						Access: "read",
+					},
 				},
 				Methods: []introspect.Method{
 					introspect.Method{

diff --git a/root.go b/root.go
index ad43163..767aed2 100644
--- a/root.go
+++ b/root.go
@@ -1,8 +1,6 @@
 package mpris
 
 import (
-	"fmt"
-
 	"github.com/godbus/dbus/v5"
 	"github.com/godbus/dbus/v5/prop"
 )
@@ -19,7 +17,8 @@ func (m *MediaPlayer2) properties() map[string]*prop.Prop {
 		"CanQuit":      newProp(false, nil),                                            // https://specifications.freedesktop.org/mpris-spec/latest/Media_Player.html#Property:CanQuit
 		"CanRaise":     newProp(false, nil),                                            // https://specifications.freedesktop.org/mpris-spec/latest/Media_Player.html#Property:CanRaise
 		"HasTrackList": newProp(false, nil),                                            // https://specifications.freedesktop.org/mpris-spec/latest/Media_Player.html#Property:HasTrackList
-		"Identity":     newProp(fmt.Sprintf("MPD on %s", m.Instance.mpd.Address), nil), // https://specifications.freedesktop.org/mpris-spec/latest/Media_Player.html#Property:Identity
+		"Identity":     newProp("Plattenalbum", nil), // https://specifications.freedesktop.org/mpris-spec/latest/Media_Player.html#Property:Identity
+		"DesktopEntry":  newProp("de.wagnermartin.Plattenalbum", nil), // https://specifications.freedesktop.org/mpris-spec/latest/Media_Player.html#Property:Identity
 		// Empty because we can't add arbitary files in...
 		"SupportedUriSchemes": newProp([]string{}, nil), // https://specifications.freedesktop.org/mpris-spec/latest/Media_Player.html#Property:SupportedUriSchemes
 		"SupportedMimeTypes":  newProp([]string{}, nil), // https://specifications.freedesktop.org/mpris-spec/latest/Media_Player.html#Property:SupportedMimeTypes
```

Works pretty well, though I've seen it fail when running mpd-mpris as a systemd daemon, for whatever reason. From my experience, this integration with Gnome requires the above `Identity` field to be equal to the `Name` field in the `.desktop` file.

**Comment by SoongNoonien** [comment]
Why not propose this over on their github? Perhaps they could make this configurable so one can select an arbitrary `.desktop` file. But this could very well be out of scope for them.

**Comment by rien333** [comment]
> Perhaps they could make this configurable so one can select an arbitrary .desktop file.

That may well be a valid suggestion, thanks. I was worried it might be out of scope, however, since I'm not sure how exclusive this is to Gnome. Will do some more research!
