### ISSUE TITLE
Window no longer fits on RasPi touchscreen

### ISSUE THREAD

**Issue by bhartshorn** [SoongNoonien/plattenalbum#107]
Hello,

I'm looking in to solutions on my end (half scaling?), but wanted to report this. I'm assuming that your primary use-case isn't tiny displays. I was a happy mpdevil user as a music player kiosk using a raspberry pi and official touchscreen display (800 x 480 resolution).

After updating to the latest plattenalbum version, the player controls are off the bottom of the screen and the preferences window doesn't fit on the display either (I can't even close it because it's locked in place and the close buttons are off screen). I'll try to get a screenshot but it shouldn't be too hard to picture.

Consider this a plea to support smaller screen resolutions. Thanks for sharing your efforts on this project, it's greatly appreciated!

**Comment by SoongNoonien** [comment]
Hi!

> I'm assuming that your primary use-case isn't tiny displays.

No, not really. But if I have the right idea how to support tiny displays from a design perspective it shouldn't be that hard to implement with GTK4/libadwaita. I don't want to make sacrifices on the desktop/normally-sized-display usability.

> I was a happy mpdevil user as a music player kiosk using a raspberry pi and official touchscreen display (800 x 480 resolution).

Reducing the minimal height to 480px results in the following aspect ratio:
![Bildschirmfoto vom 2024-03-22 16-05-34](https://github.com/SoongNoonien/plattenalbum/assets/49582808/0b19fc3b-8878-4da2-84b4-291e543b38dc)

I'm not sure if this is usable. Would that be enough for your use case?

> After updating to the latest plattenalbum version, the player controls are off the bottom of the screen...

Currently the minimum window height is 600px.

> ...and the preferences window doesn't fit on the display either...

This should be better with libadwaita-1.5 (after I have ported to it) where dialogs like the preferences window are restricted in size by their parent window.

> ...(I can't even close it because it's locked in place and the close buttons are off screen).

What do you mean "locked in place"? Can't you move it with a mouse and keyboard?

**Comment by bhartshorn** [comment]
> I'm not sure if this is usable. Would that be enough for your use case?

I think so. In the prior version I was able to slightly shrink the current album art for a little more space for the current playlist. Even if that functionality is no longer available, I think it's still workable
 
> What do you mean "locked in place"? Can't you move it with a mouse and keyboard?

I plugged in a mouse and it doesn't allow me to move the window. I could probably exit it with a combination of keyboard inputs though. 

I also can't reach all the available preferences, but I wouldn't ask you to add scrolling or anything just for me.

The preferences window being unmovable seems related to the following link, and I'm going to try the dconf setting to unlock it, but I'm not sure it will work. I'm running plattenalbum directly in cage so I don't know if gnome settings apply here. https://askubuntu.com/questions/109321/how-to-detach-modal-dialogs-from-main-window-popup-dialogs-attached-to-window-t

**Comment by SoongNoonien** [comment]
> I think so. In the prior version I was able to slightly shrink the current album art for a little more space for the current playlist. Even if that functionality is no longer available, I think it's still workable

Ok, I've reduced the minimal height in master.

> I plugged in a mouse and it doesn't allow me to move the window. I could probably exit it with a combination of keyboard inputs though.

ESC should work and maybe something like the alt key or meta to move the window.

> I also can't reach all the available preferences, but I wouldn't ask you to add scrolling or anything just for me.

It is already scrollable just the default size is to large for your screen. But this should be resolved with the new dialogs of libadwaita-1.5.

> The preferences window being unmovable seems related to the following link, and I'm going to try the dconf setting to unlock it, but I'm not sure it will work. I'm running plattenalbum directly in cage so I don't know if gnome settings apply here. https://askubuntu.com/questions/109321/how-to-detach-modal-dialogs-from-main-window-popup-dialogs-attached-to-window-t

Yes, this is the case under GNOME. But I don't know what "I'm running plattenalbum directly in cage" means.

**Comment by bhartshorn** [comment]
I installed the -git package and it looks great. Previously I could resize the now playing cover art to have more space for songs, but that's not absolutely essential. Thanks again.
