### ISSUE TITLE
Artist search fails with hyphen

### ISSUE THREAD

**Issue by Richjn** [SoongNoonien/plattenalbum#112]
Hi
Search fails on the artists listing when the name contains a hyphen i.e T-Bone Burnett
The track search doesn't display this issue.

Not hard to workaround by simply searching for "Bone" 

![Screenshot from 2024-04-20 07-05-03](https://github.com/SoongNoonien/plattenalbum/assets/117611987/2fff0831-b286-45fa-83e5-8497c410e12a)

**Comment by SoongNoonien** [comment]
It seems to work over here:
![Bildschirmfoto vom 2024-04-20 10-51-59](https://github.com/SoongNoonien/plattenalbum/assets/49582808/1bf389f6-6608-4aae-a6f3-29805982cb2f)

Maybe you didn't use the usual hyphen form the keyboard "-" in the tags? There are quite a few other "dashes" that can be confused with a hyphen https://en.wikipedia.org/wiki/Dash.

**Comment by Richjn** [comment]
> Maybe you didn't use the usual hyphen form the keyboard "-" in the tags? 

Good catch!
It appears some of my tags are using the wrong form of dash (not added by me) the version being used looks identical but plainly isn't.

Closing as not a Plattenalbum issue.
