### ISSUE TITLE
Album coverarts not showing

### ISSUE THREAD

**Issue by greenvorbisfan** [SoongNoonien/plattenalbum#124]
I didn’t have time to notice at what point this happened, but the covers are not displayed even in the flatpak version (2.1.1).
Ubuntu 24.04
Plattenalbum 2.1.1 (compiled from git; also tried the flathub version).
![изображение](https://github.com/SoongNoonien/plattenalbum/assets/7892693/b898bff3-dc57-40e9-944e-77724427ea97)

**Comment by SoongNoonien** [comment]
What MPD version do you use and how do you connect to the server?

**Comment by greenvorbisfan** [comment]
mpd 0.24-git (v0.23.15-1273-g964e18ab4)
Connecting to a remote server using a password.

**Comment by greenvorbisfan** [comment]
For comparison, covers are displayed normally in the MAFA client for Android. But it needs to indicate the path to the music via HTTP — I didn’t find such settings here.
![изображение](https://github.com/SoongNoonien/plattenalbum/assets/7892693/2a22fbd0-55c9-41b2-b88e-5525fd67b2d6)

**Comment by SoongNoonien** [comment]
For remote connections Plattenalbum only supports the cover transmission of MPD. So you either have to include the covers in the tags of the music files or they have to lay in the same directory as the corresponding music file and need to be named `cover.EXT` where `EXT` is either `png`, `jpg` or `webp`.

**Comment by greenvorbisfan** [comment]
Understood thanks. Should the file name be `cover.ext` or will a `folder.ext` work too? (In my collection, all covers are named `folder.ext`)

**Comment by SoongNoonien** [comment]
Currently MPD just supports `cover.ext`.

> In my collection, all covers are named `folder.ext`

This is probably the cause of the problem. If you rename them to `cover.ext` they should show up.

**Comment by greenvorbisfan** [comment]
So, I’ll do a massive renaming. 😊 Thanks for the help!
