### ISSUE TITLE
Add setting to apped to queue as default action

### ISSUE THREAD

**Issue by rooiratel** [SoongNoonien/plattenalbum#125]
Currently the only way that I know of to append to the queue is to right click on a song, and then click on append.

I would like the default behavior to be that when I click or double click on a song, that it is appended to the play queue.

**Comment by SoongNoonien** [comment]
You can also use drag and drop or just do a middle click.

**Comment by rooiratel** [comment]
Thanks that works. I am not sure if I would have figured that out on my own. Is it possible to add that to the "shortcuts" screen?

**Comment by SoongNoonien** [comment]
No, unfortunately not. Only keyboard shortcuts and touchpad gestures are supported.

**Comment by SoongNoonien** [comment]
But if you had clicked on the help entry in the main menu or pressed `F1` you would have been redirected to a short summary of the features which incidentally includes both the middle click and the drag and drop. ;-)

**Comment by rooiratel** [comment]
You are right. I missed that. My bad.
