### ISSUE TITLE
UI confusion: album only seems to have one song

### ISSUE THREAD

**Issue by auroraanna** [SoongNoonien/plattenalbum#128]
I have an album of which each song is created by a different artist. The album is published under a label. If I click on one of the artist on the left side scroll list and then click on the album this is what is see:
![an image of plattenalbum's ui. an album is being viewed](https://github.com/SoongNoonien/plattenalbum/assets/81317317/de7630c7-819f-44c2-9321-0ad8e4f3396f)

This does not make sense to me. It looks like it is supposed to be the whole album because the album cover art and the album title is shown but then there is only one song. The album has 6 songs. Either all songs of the album should be shown or the album cover art, etc. should not be shown as big and there should be some notice that this song is part of an album so when you click on the notice you get to the whole album. The current state is bad UI imo.

**Comment by SoongNoonien** [comment]
> The current state is bad UI imo.

To me it looks more like bad tagging ;-)

>  Either all songs of the album should be shown...

This is already achievable. Simply add each artist which appears on the album as `AlbumArtist` (tags can have multiple values). After that this album will be shown as a whole under each of the artists.
