### ISSUE TITLE
[Circle]: Consider shortening name

### ISSUE THREAD

**Issue by bragefuglseth** [SoongNoonien/plattenalbum#139]
Breakout thread from the ongoing [GNOME Circle review](https://gitlab.gnome.org/Teams/Circle/-/issues/219) of the app.

The name "Plattenalbum" is fun, albeit a little convoluted (and hard to pronounce for non-Germans :smile:). Maybe it could be shortened to just "Platten"? I'm not gonna make this a blocker for Circle personally, but I can't guarantee that the cross-reviewer will agree. You can keep it for now and close this issue if you'd like to.

**Comment by SoongNoonien** [comment]
Hm, this is kind of a blocker for me... I've changed the name relatively recently after long and careful thought specifically to comply with the guidelines. So, I rather don't want to change the name again.

**Comment by bragefuglseth** [comment]
If it's a blocker on your end, keep it. The cross-reviewer can't leave it hanging on this one thing anyways, should they need shortening.
