### ISSUE TITLE
Right clicked list items remain highlighted 

### ISSUE THREAD

**Issue by rien333** [SoongNoonien/plattenalbum#143]
# Description

Not sure if this is a bug, because Nautilus does the same, but it confuses me sometimes that a list item (either in the queue or in an album's tracklist) remains highlight after having right clicked it. 

I think it would make more sense for the highlight to disappear after the list item loses focus (or after some other event)

Feel free to close if this is just a GTK/Gnome oddity. 

# To Reproduce

[Screencast from 2024-07-20 19-29-53.webm](https://github.com/user-attachments/assets/cffe8ab5-2ff9-460a-8e30-532f143bc67b)

**Comment by SoongNoonien** [comment]
I noticed that as well. I'm fairly certain that this is a GTK or maybe libadwaita bug.

**Comment by rien333** [comment]
FWIW: just noticed that this is largely gone from nautilus and plattenalbum.
