### ISSUE TITLE
Album loading performance

### ISSUE THREAD

**Issue by SoongNoonien** [SoongNoonien/plattenalbum#40]
The album(-cover) loading performance is improvable. This issue is to provide a place for discussion on that topic. It has been extracted from #39.

**Comment by SoongNoonien** [comment]
The newest commit (4245b40b3d81a44d97ba92a62c96f5ab5993a633) changes the album loading a bit. Initial GUI blocks in combination with large artists (many albums) should now be gone. I also separated the fetching/locating of the covers from the actual loading of the albums which decreases the initial time needed to display the albums without their covers. Sadly the overall time did not really decrease. The complete procedure is now run in a separate thread using python's threading module but this should manly increase the reliability and not the performance.

@dgcampea It would be really nice if you could test these changes.

**Comment by dgcampea** [comment]
I can confirm that 4245b40 in general improves the responsiveness of the GUI (previously it would stutter when changing between album artists).

**Comment by dgcampea** [comment]
Might be worth a look (haven't looked too deeply into it yet):
- https://github.com/begnac/ampd
  - https://github.com/begnac/gampc

**Comment by SoongNoonien** [comment]
I'll close this now. The album loading has been changed quite a bit since I opened this issue. I don't currently think that I can improve this significantly any time soon. The main issue back than was related to showing all albums at once, which I don't support anymore. So I'd say the issue isn't that big at the moment.
